### ISSUE TITLE
Missing DSP endpoint requests on the main API page.

### ISSUE THREAD

**Issue by PJIonGis** [department-for-transport-public/D-TRO#32]
1. Provide full details of the endpoint call with parameters and body including the payload being used, e.g. ​
N/A

2. Provide full error message from D-TRO application, e.g.​
N/A

3. Provide the date and time of the API call to enable us to search to logs for more information​
06/11/24 13:15

4. Provide expected and actual behaviour​

Expected behaviour - We are a DSP and expect to see Section 9 Endpoints available for TRA's and / or DSPs. It was there yesterday but when we login this morning it is missing. 
Actual behaviour - Section 9 Endpoints available for TRA's and / or DSPs missing

5. Provide steps to reproduce

![s5](https://github.com/user-attachments/assets/423e960b-b48a-4064-9a2c-15f1b93d9d86)

![s6](https://github.com/user-attachments/assets/74fb926e-b04d-461e-9aa2-e277e68d8b08)

6. Provide what version of Schema you are using​
3.2.4

7. Provide any additional context, if applicable

Please restore the DSP access asap

**Comment by stm-john-cooper** [comment]
First and foremost, Digital Solution Providers' (DSP) definitely have access to the above endpoints. The endpoints are still there and are reachable. The issue is that the API documentation for Consumer was uploaded and incorrectly labelled as the documention for Publisher. The correct document has been uploaded. We apologise for this error.
